# Generated by Django 5.2 on 2025-04-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studyplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
