# Generated by Django 5.2 on 2025-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_studyplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral',
        ),
    ]
