# Generated by Django 5.2 on 2026-01-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studyplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
